import React, { useMemo, useState } from 'react'
import { financialHelpFor } from '../lib/financialHelp'
import { Badge, Card, Select, InfoTip } from './ui'
import { Icon, fmtCLP } from '../lib/helpers'
import { CATEGORIES } from '../data'
import { useBanks } from '../services/banksService'

const INPUT = 'w-full h-10 rounded-xl border border-[var(--line)] bg-[var(--bg)] px-3 text-[13px] focus:outline-none focus:border-[var(--ink)]'
const BLANK_EXPENSE = { kind:'expense', name:'', amount:'', category:'hogar', bank:'bchile', method:'tarjeta', type:'debito', dayOfMonth:5, active:true, autoRegister:false, comisionBancaria:false, medio:'', lastChargedMonth:null }
const BLANK_INCOME = { kind:'income', name:'', amount:'', category:'sueldo', bank:'', method:'transfer', type:'debito', dayOfMonth:1, active:true, autoRegister:true, lastChargedMonth:null }
const relationBlank = kind => ({ kind, name:'', personName:'', amount:'', category:kind==='payable'?'por_pagar':'por_cobrar', dueDate:'', description:'', notes:'', status:'pending', active:true, autoRegister:false })

function monthKey() { const parts=new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'2-digit',timeZone:'America/Santiago'}).formatToParts(new Date());return `${parts.find(p=>p.type==='year')?.value}-${parts.find(p=>p.type==='month')?.value}` }
function todayStart(){const d=new Date();return new Date(d.getFullYear(),d.getMonth(),d.getDate())}
function nextMovement(item,currentMonth){const today=todayStart();const day=Math.max(1,Number(item.dayOfMonth||1));const charged=item.lastChargedMonth===currentMonth;let date=new Date(today.getFullYear(),today.getMonth(),day);if(charged)date=new Date(today.getFullYear(),today.getMonth()+1,day);return{date,overdue:!charged&&date<today}}
function shortDate(date){return new Intl.DateTimeFormat('es-CL',{day:'2-digit',month:'short'}).format(date)}
function catFor(id){return CATEGORIES.find(item=>item.id===id)||CATEGORIES.find(item=>item.id==='otros')}
function Metric({label,value,detail,tone='default', info}) {
  const help = info || financialHelpFor(label); const cls=tone==='dark'?'bg-[var(--ink)] text-[var(--bg)] border-transparent':tone==='danger'?'bg-red-50 text-red-800 border-red-100':tone==='warning'?'bg-[var(--amber-soft)] text-[var(--amber-ink)] border-transparent':'bg-[var(--bg-elev)] border-[var(--line)]';return <div className={`rounded-2xl border p-4 min-h-[110px] ${cls}`}><div className="flex items-center gap-1.5"><div className="text-[10px] uppercase tracking-[0.11em] font-bold opacity-60">{label}</div>{help && <InfoTip content={help}/>}</div><div className="font-mono text-[22px] font-bold mt-3">{value}</div><div className="text-[10px] opacity-65 mt-1.5">{detail}</div></div>}
function Field({label,children,hint}){return <label className="block"><span className="block text-[9.5px] uppercase tracking-[0.1em] text-[var(--muted)] mb-1.5">{label}</span>{children}{hint&&<span className="block text-[9px] text-[var(--muted)] mt-1">{hint}</span>}</label>}
function Modal({title,onClose,children}){return <div className="fixed inset-0 z-50 flex items-end md:items-center justify-center p-0 md:p-4"><div className="absolute inset-0 bg-black/40 backdrop-blur-sm" onClick={onClose}/><div className="relative w-full md:max-w-[560px] max-h-[92vh] overflow-y-auto rounded-t-2xl md:rounded-2xl bg-[var(--bg-elev)] border border-[var(--line)] shadow-2xl"><div className="sticky top-0 z-10 px-4 py-3.5 border-b border-[var(--line)] bg-[var(--bg-elev)] flex items-center justify-between"><div className="text-[14px] font-bold">{title}</div><button onClick={onClose} className="w-8 h-8 rounded-lg border border-[var(--line)] grid place-items-center"><Icon name="x" size={13}/></button></div>{children}</div></div>}

function Editor({initial,banks,onClose,onSave}){
  const [form,setForm]=useState(initial);const set=(key,value)=>setForm(current=>({...current,[key]:value}));const relation=['receivable','payable'].includes(form.kind);const valid=relation?String(form.personName||form.name||'').trim()&&Number(form.amount)>0:String(form.name||'').trim()&&Number(form.amount)>0
  return <><div className="p-4 grid grid-cols-2 gap-3">{relation?<>
    <div className="col-span-2"><Field label={form.kind==='payable'?'A quién debes':'Quién te debe'}><input value={form.personName||''} onChange={event=>{set('personName',event.target.value);set('name',event.target.value)}} className={INPUT}/></Field></div>
    <Field label="Monto"><input type="number" min="0" value={form.amount} onChange={event=>set('amount',event.target.value)} className={`${INPUT} font-mono`}/></Field><Field label="Fecha esperada"><input type="date" value={form.dueDate||''} onChange={event=>set('dueDate',event.target.value)} className={INPUT}/></Field>
    <div className="col-span-2"><Field label="Descripción"><input value={form.description||''} onChange={event=>set('description',event.target.value)} className={INPUT}/></Field></div><Field label="Categoría"><Select value={form.category} onChange={value=>set('category',value)} options={CATEGORIES.map(item=>({value:item.id,label:`${item.icon} ${item.label}`}))}/></Field><div className="col-span-2"><Field label="Nota"><input value={form.notes||''} onChange={event=>set('notes',event.target.value)} className={INPUT}/></Field></div>
  </>:<>
    <div className="col-span-2"><Field label={form.kind==='income'?'Fuente de ingreso':'Nombre'}><input value={form.name||''} onChange={event=>set('name',event.target.value)} className={INPUT}/></Field></div><Field label="Monto mensual"><input type="number" min="0" value={form.amount} onChange={event=>set('amount',event.target.value)} className={`${INPUT} font-mono`}/></Field><Field label="Día del mes"><input type="number" min="1" max="31" value={form.dayOfMonth||''} onChange={event=>set('dayOfMonth',event.target.value)} className={`${INPUT} font-mono`}/></Field>
    <Field label="Categoría"><Select value={form.category} onChange={value=>set('category',value)} options={CATEGORIES.map(item=>({value:item.id,label:`${item.icon} ${item.label}`}))}/></Field>{form.kind==='expense'&&<Field label="Banco"><Select value={form.bank||''} onChange={value=>set('bank',value)} options={[{value:'',label:'Sin banco'},...banks.map(item=>({value:item.id,label:item.label}))]}/></Field>}
    {form.kind==='expense'&&<><Field label="Forma de cobro"><select className={INPUT} value={form.type||'debito'} onChange={event=>set('type',event.target.value)}><option value="debito">Directo / débito</option><option value="credito">Tarjeta de crédito</option></select></Field><Field label="Clasificación"><select className={INPUT} value={form.comisionBancaria?'commission':'fixed'} onChange={event=>{const commission=event.target.value==='commission';set('comisionBancaria',commission);if(commission)set('category','comision_bancaria')}}><option value="fixed">Gasto fijo</option><option value="commission">Comisión bancaria</option></select></Field></>}
    <label className="col-span-2 flex items-center gap-2 text-[11px]"><input type="checkbox" checked={form.autoRegister!==false} onChange={event=>set('autoRegister',event.target.checked)}/>{form.kind==='income'?'Ingreso automático':'Registro automático'}</label>
  </>}</div><div className="px-4 py-3 border-t border-[var(--line)] flex justify-end gap-2"><button onClick={onClose} className="h-9 px-3 text-[11px] text-[var(--muted)]">Cancelar</button><button disabled={!valid} onClick={()=>valid&&onSave({...form,amount:Number(form.amount||0),dayOfMonth:Number(form.dayOfMonth||1)})} className="h-9 px-4 rounded-xl bg-[var(--ink)] text-[var(--bg)] text-[11px] font-semibold disabled:opacity-40">Guardar</button></div></>
}

function ItemRow({item,kind,onEdit,onDelete,onPrimary,onPause,currentMonth,banks}){
  const cat=catFor(item.category);const paid=item.status==='paid';const movement=kind==='expense'||kind==='income'?nextMovement(item,currentMonth):null;const due=relationDate(item);const overdue=kind==='receivable'||kind==='payable'?(!paid&&due&&due<todayStart()):movement?.overdue;const bank=banks.find(row=>row.id===item.bank);let secondary=''
  if(kind==='expense')secondary=`${item.type==='credito'?'Se carga a tarjeta':'Sale directo'}${bank?` · ${bank.label}`:''}${movement?` · ${overdue?'Pendiente desde':'Próximo'} ${shortDate(movement.date)}`:''}`
  if(kind==='income')secondary=`Ingreso mensual${movement?` · ${overdue?'Pendiente desde':'Próximo'} ${shortDate(movement.date)}`:''}`
  if(kind==='receivable'||kind==='payable')secondary=`${item.description||''}${due?`${item.description?' · ':''}${overdue?'Venció':'Vence'} ${shortDate(due)}`:''}`
  const amountColor=kind==='income'||kind==='receivable'?'text-emerald-700':kind==='payable'?'text-red-700':'text-[var(--ink)]'
  const primaryLabel=kind==='expense'?'Registrar gasto':kind==='receivable'?'Marcar cobrado':kind==='payable'?'Marcar pagado':''
  return <div className={`p-3.5 flex items-start gap-3 ${paid||item.active===false?'opacity-55':''}`}><div className="w-10 h-10 rounded-xl grid place-items-center text-[18px] shrink-0" style={{background:`${cat?.color||'#888'}20`}}>{cat?.icon||'•'}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="text-[12px] font-semibold">{item.personName||item.name}</span>{kind==='expense'&&<Badge tone={item.type==='credito'?'info':'muted'}>{item.type==='credito'?'En tarjeta':'Directo'}</Badge>}{overdue&&<Badge tone="warn">Pendiente</Badge>}{paid&&<Badge tone="ok">Pagado</Badge>}{item.active===false&&<Badge tone="muted">Pausado</Badge>}</div><div className="text-[9.5px] text-[var(--muted)] mt-1 leading-relaxed">{secondary}</div>{kind==='expense'&&item.comisionBancaria&&<div className="mt-1"><Badge tone="warn">Comisión</Badge></div>}</div><div className="shrink-0 text-right"><div className={`font-mono text-[13px] font-bold ${amountColor}`}>{kind==='income'||kind==='receivable'?'+':'−'}{fmtCLP(item.amount)}</div><div className="flex items-center justify-end gap-1 mt-2">{primaryLabel&&onPrimary&&!paid&&item.active!==false&&(kind!=='expense'||item.lastChargedMonth!==currentMonth)&&<button onClick={onPrimary} className="h-8 px-2.5 rounded-lg border border-[var(--line)] text-[9px] font-semibold">{primaryLabel}</button>}{onPause&&<button onClick={onPause} className="h-8 px-2.5 rounded-lg border border-[var(--line)] text-[9px] font-semibold">{item.active===false?'Activar':'Pausar'}</button>}<button onClick={onEdit} className="w-8 h-8 rounded-lg border border-[var(--line)] grid place-items-center"><Icon name="pencil" size={11}/></button><button onClick={onDelete} className="w-8 h-8 rounded-lg bg-red-50 text-red-600 grid place-items-center"><Icon name="trash" size={11}/></button></div></div></div>
}
function relationDate(item){if(!item.dueDate)return null;const d=new Date(`${String(item.dueDate).slice(0,10)}T12:00:00`);return Number.isNaN(d.getTime())?null:d}

export default function Recurring({ recurring=[],setRecurring,onCreateRecurring,onUpdateRecurring,onDeleteRecurring,incomeList=[],onCreateIncome,onUpdateIncome,onDeleteIncome,receivablesList=[],onCreateReceivable,onUpdateReceivable,onDeleteReceivable,onMarkReceivablePaid,payablesList=[],onCreatePayable,onUpdatePayable,onDeletePayable,onMarkPayablePaid }){
  const banks=useBanks();const currentMonth=monthKey();const [tab,setTab]=useState('expense');const [editing,setEditing]=useState(null)
  const active=recurring.filter(item=>item.active);const direct=active.filter(item=>item.type!=='credito');const card=active.filter(item=>item.type==='credito');const incomeActive=incomeList.filter(item=>item.active);const receivablePending=receivablesList.filter(item=>item.status!=='paid');const payablePending=payablesList.filter(item=>item.status!=='paid')
  const directTotal=direct.reduce((s,i)=>s+Number(i.amount||0),0);const cardTotal=card.reduce((s,i)=>s+Number(i.amount||0),0);const incomeTotal=incomeActive.reduce((s,i)=>s+Number(i.amount||0),0);const receivableTotal=receivablePending.reduce((s,i)=>s+Number(i.amount||0),0);const payableTotal=payablePending.reduce((s,i)=>s+Number(i.amount||0),0)
  const pendingDirect=direct.filter(item=>item.lastChargedMonth!==currentMonth);const commissions=active.filter(item=>item.comisionBancaria)
  const upcoming=useMemo(()=>[...active.map(item=>({...item,kindLabel:item.type==='credito'?'Tarjeta':'Directo',signed:-Number(item.amount||0),...nextMovement(item,currentMonth)})),...incomeActive.map(item=>({...item,kindLabel:'Ingreso',signed:Number(item.amount||0),...nextMovement(item,currentMonth)}))].sort((a,b)=>a.date-b.date).slice(0,8),[active,incomeActive,currentMonth])
  const lists={expense:recurring,income:incomeList,receivable:receivablesList,payable:payablesList};const currentList=lists[tab]||[]
  const openNew=()=>setEditing(tab==='expense'?{...BLANK_EXPENSE}:tab==='income'?{...BLANK_INCOME}:relationBlank(tab))
  const save=async form=>{if(tab==='expense'){if(form.id)await onUpdateRecurring?.(form);else await onCreateRecurring?.(form)}if(tab==='income'){if(form.id)await onUpdateIncome?.(form);else await onCreateIncome?.(form)}if(tab==='receivable'){if(form.id)await onUpdateReceivable?.(form);else await onCreateReceivable?.(form)}if(tab==='payable'){if(form.id)await onUpdatePayable?.(form);else await onCreatePayable?.(form)}setEditing(null)}
  const remove=async item=>{if(!window.confirm('¿Eliminar este registro?'))return;if(tab==='expense')await onDeleteRecurring?.(item.id);if(tab==='income')await onDeleteIncome?.(item.id);if(tab==='receivable')await onDeleteReceivable?.(item.id);if(tab==='payable')await onDeletePayable?.(item.id)}
  const toggle= item => setRecurring?.(recurring.map(row=>row.id===item.id?{...row,active:!row.active}:row))
  const register= item => setRecurring?.(recurring.map(row=>row.id===item.id?{...row,lastChargedMonth:currentMonth}:row))
  return <div className="max-w-7xl mx-auto pb-20 flex flex-col gap-5">
    <div className="grid grid-cols-2 lg:grid-cols-5 gap-2.5"><Metric label="Ingresos mensuales" value={fmtCLP(incomeTotal)} detail={`${incomeActive.length} fuentes activas`} tone="dark"/><Metric label="Fijos directos" value={fmtCLP(directTotal)} detail={`${direct.length} salen de saldo, débito o efectivo`}/><Metric label="Cargos en tarjeta" value={fmtCLP(cardTotal)} detail={`${card.length} incluidos después en Facturación`} tone={cardTotal?'warning':'default'}/><Metric label="Por cobrar" value={fmtCLP(receivableTotal)} detail={`${receivablePending.length} pendientes`}/><Metric label="Por pagar" value={fmtCLP(payableTotal)} detail={`${payablePending.length} obligaciones`} tone={payableTotal?'danger':'default'}/></div>
    <div className="grid lg:grid-cols-[1.15fr_.85fr] gap-4"><Card padding="p-4 md:p-5"><div className="flex items-start gap-3"><div className="w-10 h-10 rounded-xl bg-[var(--accent-soft)] text-[var(--accent-ink)] grid place-items-center"><Icon name="repeat" size={16}/></div><div><div className="text-[13px] font-bold">Sin doble conteo</div><div className="text-[10.5px] text-[var(--muted)] mt-1 leading-relaxed">Los {fmtCLP(directTotal)} directos salen de tu saldo. Los {fmtCLP(cardTotal)} configurados como crédito se ven aquí como compromisos, pero el pago real se considera dentro de la factura de la tarjeta.</div></div></div><div className="grid grid-cols-2 gap-2 mt-4"><div className="rounded-xl bg-[var(--bg)] p-3"><div className="text-[9px] uppercase text-[var(--muted)]">Pendientes de registrar</div><div className="font-mono text-[18px] font-bold mt-1">{pendingDirect.length}</div></div><div className="rounded-xl bg-[var(--bg)] p-3"><div className="text-[9px] uppercase text-[var(--muted)]">Comisiones</div><div className="font-mono text-[18px] font-bold mt-1">{fmtCLP(commissions.reduce((s,i)=>s+Number(i.amount||0),0))}</div></div></div></Card><Card padding="p-4 md:p-5"><div className="text-[13px] font-bold">Próximos movimientos</div><div className="mt-3 divide-y divide-[var(--line)]">{upcoming.map(item=>{const cat=catFor(item.category);return <div key={`${item.kindLabel}:${item.id}`} className="py-2.5 flex items-center gap-2.5"><div className="w-8 h-8 rounded-lg grid place-items-center" style={{background:`${cat.color}20`}}>{cat.icon}</div><div className="min-w-0 flex-1"><div className="text-[11px] font-semibold truncate">{item.name}</div><div className={`text-[9px] mt-0.5 ${item.overdue?'text-[var(--amber-ink)]':'text-[var(--muted)]'}`}>{item.overdue?'Pendiente desde ':''}{shortDate(item.date)} · {item.kindLabel}</div></div><div className={`font-mono text-[11px] font-bold ${item.signed>=0?'text-emerald-700':''}`}>{item.signed>=0?'+':'−'}{fmtCLP(Math.abs(item.signed))}</div></div>})}</div></Card></div>
    <Card padding="p-0"><div className="p-3 border-b border-[var(--line)]"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex gap-1 overflow-x-auto">{[['expense','Gastos fijos',recurring.length],['income','Ingresos',incomeList.length],['receivable','Por cobrar',receivablePending.length],['payable','Por pagar',payablePending.length]].map(([id,label,count])=><button key={id} onClick={()=>setTab(id)} className={`h-9 px-3 rounded-xl text-[10px] font-semibold whitespace-nowrap ${tab===id?'bg-[var(--ink)] text-[var(--bg)]':'text-[var(--muted)] hover:bg-[var(--hover)]'}`}>{label} · {count}</button>)}</div><button onClick={openNew} className="h-9 px-3 rounded-xl bg-[var(--ink)] text-[var(--bg)] text-[10px] font-semibold"><Icon name="plus" size={11}/> Nuevo</button></div></div>{!currentList.length?<div className="p-10 text-center"><div className="text-[30px]">🔄</div><div className="text-[13px] font-bold mt-2">Sin registros</div><button onClick={openNew} className="mt-3 h-9 px-4 rounded-xl bg-[var(--ink)] text-[var(--bg)] text-[10px] font-semibold">Crear primero</button></div>:<div className="divide-y divide-[var(--line)]">{currentList.map(item=><ItemRow key={item.id} item={item} kind={tab} banks={banks} currentMonth={currentMonth} onEdit={()=>setEditing({...item})} onDelete={()=>remove(item)} onPause={tab==='expense'?()=>toggle(item):null} onPrimary={tab==='expense'?()=>register(item):tab==='receivable'?()=>onMarkReceivablePaid?.(item.id):tab==='payable'?()=>onMarkPayablePaid?.(item.id):null}/>)}</div>}</Card>
    {editing&&<Modal title={editing.id?'Editar registro':'Nuevo registro'} onClose={()=>setEditing(null)}><Editor initial={editing} banks={banks} onClose={()=>setEditing(null)} onSave={save}/></Modal>}
  </div>
}
